### ISSUE TITLE
StreamGroup needs additional name field

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaAPI#43]
Stream groups should contain an additional stream name field to avoid constructing it for every stream_group call.
Type should be String and name should be stream_name.

**Comment by St4NNi** [comment]
Where exactly should this be inserted ? `CreateEventStreamingGroup` will create a new stream_group and respond a `stream_group_id` this id is used to specify the stream_group. The only request that has no stream_group_id is `ReadStreamGroupMessages` this should contain the id as well. 

Adding a user-defined name gives in my opinion no additional benefit if we dont enforce a unique name which is similar or equivalent to a uuid.

**Comment by MariusDieckmann** [comment]
This is required in NATS.io to identify the underlaying stream in which the information are stored in the database (which is required to actually connect to the stream group).
