### ISSUE TITLE
Add object parts for multipart upload of objects

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaAPI#48]
We currently assume in the API and the database that individual objects are a single binary. Multipart uploads are stored in multiple parts on disk and are not merged in most object storage systems. This should be reflected in the database and API. I therefor propose a list of parts an object consists of (0..n or 1..n). This would be reflected as part of the API.
The fields are similar to those of an object:

- ID
- Hashsum
- Size
- Offset (in the original object)
- ETag
- PartNumber
- ParentObjectID

Querying would be based on batch request (give all parts of an object or paginated)
The ID is provided by the database system and can be used by a DataProxy to properly store and object.
Delete and Update actions should not be required.

- [ ] Add parts table to the database
- [ ] Add create and read requests to database

**Comment by St4NNi** [comment]
This would introduce a significant overhead on the database side. Interesting idea but will not be implemented in the near future. Close this for now.
