### ISSUE TITLE
Provide object hash in create object request

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/ArunaAPI#49]
Currently, the object hash is provided after the actual upload of the object (in the "finish upload" call). I suggest that it should be provided when the object is first created, instead.

**Comment by St4NNi** [comment]
Yes, a good idea. It will also make it easier to choose the correct hashing algorithm in-advance. I suggest that we add this functionality to the init call without removing it from the finish call. 

Some applications that make heavy use of multi-part uploads across multiple machines might not always (or never) know the hash of the full file in advance (and only know the hash of each individual part). Additionally this will also leave the current behavior compatible with newer versions without inducing a breaking change.

**Comment by mzur** [comment]
> Some applications that make heavy use of multi-part uploads across multiple machines might not always (or never) know the hash of the full file in advance (and only know the hash of each individual part).

Although at the time the "create object" request is sent, the uploads were not started, yet (on other machines). So I think there would be a good chance that the hash of the complete file is known then.
